version: '3.7'
services:
  mongodb:
    image: mongo:5.0
    volumes:
      - db_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: stalingard-showdown
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017" 
  php:
    depends_on:
     - mongodb
    image: php:apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/var/www/html
    ports:
     - "8010:80"

volumes:
  db_data:
